---
title: "location map"
author: "Linna Sun"
date: "March 13, 2017"
output: html_document
---
```{r}
library(maps)
library(ggplot2)
world_map <- map_data("world")
```

```{r}
#Creat a base plot with gpplot2
p <- ggplot() + coord_fixed() +
  xlab("") + ylab("")

#Add map to base plot
base_world_messy <- p + geom_polygon(data=world_map, aes(x=long, y=lat, group=group), 
                               colour="black ", fill="black")

base_world_messy
```
```{r}
#Creat a base plot with gpplot2
p <- ggplot() + coord_fixed() +
  xlab("") + ylab("")

#Add map to base plot
base_world_messy1 <- p + geom_polygon(data=world_map, aes(x=long, y=lat, group=group), 
                               colour="light green ", fill="light green")

base_world_messy1
```

```{r}
#Strip the map down so it looks super clean (and beautiful!)
cleanup <- 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        panel.background = element_rect(fill = 'white', colour = 'white'), 
        axis.line = element_line(colour = "white"), legend.position="none",
        axis.ticks=element_blank(), axis.text.x=element_blank(),
        axis.text.y=element_blank())

base_world <- base_world_messy1 + cleanup

base_world
```




```{r}
library(ggplot2)

setwd("~/Desktop/eeb-177/eeb-177-final-project/data_file/location/")
proboscidea <- read.csv("~/Desktop/eeb-177/eeb-177-final-project/data_file/location/formatted_location.csv", header = T, as.is = T)
head(proboscidea)

```

```{r}

map_data <- 
  base_world_messy1 + geom_point(data=proboscidea,aes(x=paleolng, y=paleolat), colour="Blue",pch=2, size=0.1, alpha=I(1)) + labs(title = "Fossil Records on World Map", x = "Longitude", y = "Latitude") + theme(plot.title = element_text(hjust = 0.5, size=18, face = "bold"), axis.title =element_text(size=10))

map_data
```

```{r}

map_data <- 
  base_world_messy1 + geom_point(data=proboscidea,aes(x=paleolng, y=paleolat, colour=accepted_rank),pch=2, size=0.1, alpha=I(1)) + labs(title = "Fossil Records according to Rank", x = "Longitude", y = "Latitude") + theme(plot.title = element_text(hjust = 0.5, size=18, face = "bold"), axis.title =element_text(size=10))

map_data
```

```{r}
library(RColorBrewer)

myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(0, 50))

map_data <- 
  base_world_messy + geom_point(data=proboscidea,aes(x=paleolng, y=paleolat, colour=max_ma),pch=2, size=0.2, alpha=I(1)) + labs(title = "Fossil Records according to Time", x = "Longitude", y = "Latitude") + theme(plot.title = element_text(hjust = 0.5, size=18, face = "bold"), axis.title =element_text(size=10)) + sc

map_data
```









