---
title: "range_graph"
author: "Linna Sun"
date: "March 9, 2017"
output: html_document
---

```{r}
library(ggplot2)

setwd("~/Desktop/eeb-177/eeb-177-final-project/data_file/occurence_graph/")
proboscidea <- read.csv("~/Desktop/eeb-177/eeb-177-final-project/data_file/occurence_graph/manipulated-data.csv", header = F, as.is = T)
names(proboscidea) <- c("genus", "species", "minage","maxage")
head(proboscidea)

```



```{r}
library(tidyr)
library(dplyr)

diversity <- proboscidea %>% gather(key = type, value = age, minage, maxage) %>% mutate(count = ifelse(type == "maxage", 1, -1)) %>% group_by(age) %>% summarise(count = sum(count))  %>% arrange(age,count) %>% mutate(diversity = cumsum(count)) 

ggplot(diversity, aes(x = age, y = diversity)) + geom_step()
```



```{r}
library(forcats)
proboscidea_occ <- ggplot(proboscidea, aes( x = fct_reorder(species, minage, .desc = T), maxage, colour = genus))

proboscidea_occ + geom_linerange(aes(ymin = minage, ymax = maxage + 0.5)) + theme(legend.position="none") +  coord_flip() +  theme(axis.text.y = element_text(size=4)) + scale_y_continuous(limits=c(0, 60), expand = c(0, 0), breaks=c (0, 10, 20, 30, 40, 50, 60)) + labs(title = "Proboscidea Fossil Occurrences", x = "Species", y = "Ma ago") + theme(plot.title = element_text(hjust = 0.5, size=22, face = "bold"), axis.title =element_text(size=20)) 
```












